name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build tests
      run: cmake --build build -t build_tests
    - name: Run tests
      run: cmake --build build -t test
